spring:
  mail:
    #\u90AE\u4EF6\u53D1\u9001\u670D\u52A1\u5668\u5730\u5740
    host: smtp.qq.com
    #\u90AE\u4EF6\u53D1\u9001\u8D26\u53F7
    username: 3473532212@qq.com
    #\u90AE\u4EF6\u670D\u52A1\u7684\u7B2C\u4E09\u65B9\u6388\u6743\u7801\uFF0C\u4E0D\u662Fqq\u5BC6\u7801
    password: kvgdbrhvsabadbga
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          debug: true

  servlet:
    multipart:
      #      \u6240\u6709\u8BF7\u6C42\u6587\u4EF6\u5927\u5C0F
      max-request-size: 10MB
      #      \u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
      max-file-size: 100MB
      enabled: true
