spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rx06?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GTM+8
    username: root
    password: 123456

#Mtbatis\u914D\u7F6E
mybatis:
  #mybatis\u914D\u7F6E\u6587\u4EF6\u7684\u8DEF\u5F84
  mapper-locations: com/hcy/mapper/*.xml
  type-aliases-package: com.hcy.entity
  configuration:
    #\u4E8C\u7EA7\u7F13\u5B58
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #\u9010\u6E10\u56DE\u586B
    use-generated-keys: true
    #\u61D2\u52A0\u8F7D
    lazy-loading-enabled: true
    #\u79EF\u6781\u52A0\u8F7D
    aggressive-lazy-loading: false
    #\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true


