spring:
  servlet:
    multipart:
      #      \u5355\u4E2A\u6587\u4EF6\u7684\u5C0F
      max-file-size: 10MB
      #      \u6240\u6709\u8BF7\u6C42\u6587\u4EF6\u7684\u5927\u5C0F
      max-request-size: 100MB
      #      \u5F00\u542F\u6587\u4EF6\u4E0A\u4F20
      enabled: true
