#\u9759\u6001\u8D44\u6E90\u8BBF\u95EE\u524D\u7F00
#spring:
#  mvc:
#    static-path-pattern: /hello/**
spring:
  web:
    resources:
      static-locations: classpath:/hi/
  mvc:
    static-path-pattern: /hello/**
